package_name: arlecchino
genshin_id: 10000096
key: arlecchino
icd_groups:
  - group_name: ICDGroupArlecchinoElementalArt
    reset_timer: 600
    ele_app_sequence:
      [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    damage_sequence: [1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}
    attack_4:
      - 3 # 4-Hit DMG|{param3:F1P}+{param3:F1P}
      - 3 # 4-Hit DMG|{param3:F1P}+{param3:F1P}
    attack_5:
      - 4 # 5-Hit DMG|{param6:F1P}
    attack_6:
      - 5 # 6-Hit DMG|{param5:F1P}
    charge:
      - 6 # Charged Attack DMG|{param6:F1P}
    collision:
      - 8 # Plunge DMG|{param6:F1P}
    lowPlunge:
      - 9 # Low/High Plunge DMG|{param7:P}/{param8:P}
    highPlunge:
      - 10 # Low/High Plunge DMG|{param7:P}/{param8:P}
    blooddebt:
      - 11 # Blood Debt DMG Increase|{param11:F2P}
  skill:
    skillSpike:
      - 0 # Spike Skill DMG|{param0:F1P}
    skillFinal:
      - 1 # Final Skill DMG|{param1:F1P}
    skillSigil:
      - 2 # Blood-Debt Sigil DMG|{param2:F1P}
  burst:
    burst:
      - 0 # Burst DMG|{param0:F1P}
